
- 列是第1轴，行是第0轴

# NumPy
- python 科学计算 第二章

In [1]:
import numpy as np
print dir(np)

['ALLOW_THREADS', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'PackageLoader', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '__NUMPY_SETUP__', '__all__', '__builtins__', '__config__', '__doc__', '__file__', '__git_revision__', '__mkl_version__', '__name__', '__package__', '__path__', '__version__', '_globals', '_import_tools', '_mat', 'abs', 'absolute', 'absolute_import', 'add', 'add_docstring', 'add_newdoc', 'add_newdoc_ufunc', 'add_newdocs

## 一、ufunc 运算
- ufunc是universal function的缩写，它是一种能对数组中每个元素进行操作的函数
- python 科学计算 http://hyry.dip.jp/tech/book/page/scipy/numpy_ufunc.html

- 对于单个元素，math库里的函数计算速度快得多
- 而对于数组元素，则采用numpy库里的函数计算。

In [2]:
import math
import numpy as np

print type(math.sin(10))  # 结果类型不一样
print type(np.sin(10))

<type 'float'>
<type 'numpy.float64'>


In [4]:
# item() 方法，获取数组中单个元素，并返回标准的Python数值类型
a = np.arange(6).reshape(2,3)
b = a.item(1,2) # 和 a[1,2] 类似
print type(b)  # Python 数值类型
print type(a[1,2]) # numpy中定义的类型

<type 'int'>
<type 'numpy.int32'>


### 1 基本运算

#### 1.1 数组运算符及其对应的 ufunc函数

> * y = x1 + x2 |	add(x1, x2 [, y])
> * y = x1 - x2 |		subtract(x1, x2 [, y])
> * y = x1 * x2 |		multiply (x1, x2 [, y])
> * y = x1 / x2 |		divide (x1, x2 [, y]), 如果两个数组的元素为整数，那么用整数除法
> * y = x1 / x2 |		true_divide (x1, x2 [, y]), 总是返回精确的商
> * y = x1 // x2 |		floor_divide (x1, x2 [, y]), 总是对返回值取整
> * y = -x |		negative(x [,y])
> * y = x1**x2 |		power(x1, x2 [, y])
> * y = x1 % x2 |		remainder(x1, x2 [, y]), 或mod(x1, x2, [, y])


 + ** 注意：**
 > 除号‘/’的意义根据是否激活 \__future\__.division 会有所不同

- NumPy为数组定义了各种数学运算操作符，因此计算两个数组相加可以简单地写为a+b，而np.add(a,b,a)则可以用a+=b表示

In [3]:
a = np.arange(0,4)
b = np.arange(1,5)
print a
print b

c = np.add(a,b)  # 两个参数对应元素之后
print c

d = np.add(a,b,a) # 第三个参数为out，即指定结果保存位置
print d
print a

[0 1 2 3]
[1 2 3 4]
[1 3 5 7]
[1 3 5 7]
[1 3 5 7]


- 数组对象支持操作符，极大地简化了算式的编写，不过要注意如果算式很复杂，并且要运算的数组很大，将会因为产生大量的中间结果从而降低程序的运算效率。
- 例如：假设对a、b、c三个数组采用算式“x=a*b+c”计算，那么它相当于：
> * t = a * b
> * x = t + c
> * del t
- 也就是说需要产生一个临时数组t保存乘法的运算结果，然后再产生最后的结果数组x。
- 我们可以将算式分解为下面的两行语句，以减少一次内存分配：
> * x = a*b
> * x += c

In [6]:
v = [0.5,0.75,1.0,1.5,2.0]
m = [v,v,v] # matrix of numbers

print v
m

[0.5, 0.75, 1.0, 1.5, 2.0]


[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

### 1.2 比较和布尔运算

> * y = x1 == x2 |		equal(x1, x2 [, y])
> * y = x1 != x2 |		not_equal(x1, x2 [, y])
> * y = x1 < x2  |		less(x1, x2, [, y])
> * y = x1 <= x2 |		less_equal(x1, x2, [, y])
> * y = x1 > x2	 |	greater(x1, x2, [, y])
> * y = x1 >= x2 |		greater_equal(x1, x2, [, y])

- 使用比较运算符（“==”、“>”）对两个数组进行比较，将返回一个布尔数组

In [6]:
a = np.array([1,2,3]) < np.array([3,2,1])
print a

[ True False False]


- 由于Python中的布尔运算使用and、or和not等关键字，它们无法被重载，因此数组的布尔运算只能通过相应的ufunc函数进行。
 + 这些函数名都以“logical_”开头
 > * np.logical_and、np.logical_not、np.logical_or、np.logical_xor

In [8]:
a = np.arange(5)
b = np.arange(4,-1,-1)
c = a == b
d = a > b
e = np.logical_or(a==b,a>b) # 和 a >= b 相同
print a
print b
print c
print d
print e

[0 1 2 3 4]
[4 3 2 1 0]
[False False  True False False]
[False False False  True  True]
[False False  True  True  True]


In [11]:
print np.any(a==b) # 只要数组中有一个值为True，则any()返回True
print np.all(a==b) # 只有数组的全部元素都为True，all()才返回True

True
False


— 以“bitwise_”开头的函数是比特运算函数
> * 包括bitwise_and、bitwise_not、bitwise_or和bitwise_xor等
> * 也可使用操作符，”&”、”~”、”|”和”^”等。

- 对于布尔数组来说，比特运算和布尔运算的结果相同。
> 在使用时要注意，比特运算符的优先级比比较运算符高，因此需要使用括号提高比较运算的运算优先级。

In [12]:
c = (a==b)|(a > b)
print c

[False False  True  True  True]


- 整数数组的比特运算和C语言的比特运算相同，在使用时要注意元素类型的符号

In [13]:
a = ~np.arange(5) # 2位符号整数，因此对正数按位取反将得到负数
b = ~np.arange(5,dtype = np.uint8) # 对8位无符号整数数组进行比特取反运算
print a
print b

[-1 -2 -3 -4 -5]
[255 254 253 252 251]


### 2 自定义 ufunc函数 
- 用Python很容易实现对每个元素进行计算的程序，再通过frompyfunc()将程序转换成ufunc函数，就可以方便地用所产生的ufunc函数对数组进行计算了。

In [16]:
def triangle_wave(x, c, c0, hc):
    x = x - int(x) # 三角波的周期为1，因此只取x坐标的小数部分进行计算
    if x >= c: r = 0.0
    elif x < c0: r = x / c0 * hc
    else: r = (c-x) / (c-c0) * hc
    return r

In [19]:
x = np.linspace(0, 2, 1000) # 先使用列表推导式计算出一个列表，然后用array()将列表转换为数组。
y1 = np.array([triangle_wave(t, 0.6, 0.4, 1.0) for t in x])

- frompyfunc()
> frompyfunc(func, nin, nout)
+ func是计算单个元素的函数，nin是func的输入参数的个数，nout是func的返回值个数

In [21]:
triangle_ufunc1 = np.frompyfunc(triangle_wave, 4, 1)
y2 = triangle_ufunc1(x, 0.6, 0.4, 1.0)

print y2.dtype # 返回的数组的元素类型是object
y2 = y2.astype(np.float) # 调用数组的astype()方法将其转换为双精度浮点数组
print y2.dtype

object
float64


### 3 广播
- 要求这两个数组的形状相同。
- 如果形状不同，会进行如下的广播(broadcasting)处理：
> 1. 让所有输入数组都向其中维数最多的数组看齐，shape属性中不足的部分都通过在前面加1补齐。
> 2. 输出数组的shape属性是输入数组的shape属性的各个轴上的最大值。
> 3. 如果输入数组的某个轴的长度为1或与输出数组的对应轴的长度相同时，这个数组能够用来计算，否则出错。
> 4. 当输入数组的某个轴的长度为1时，沿着此轴运算时都用此轴上的第一组值。

In [39]:
a = np.arange(0,60,10).reshape(-1,1)
b = np.arange(0,5)
print a
print a.shape
print b
print b.shape
print '----------------------'
c = a + b 
print c
print c.shape
print '----------------------'
b.shape = 1,5 # 规则1
print b
print b.shape
print '----------------------'
b = b.repeat(6,axis = 0) # 规则2
a = a.repeat(5,axis = 1)
print b
print b.shape
print a
print a.shape

[[ 0]
 [10]
 [20]
 [30]
 [40]
 [50]]
(6L, 1L)
[0 1 2 3 4]
(5L,)
----------------------
[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]
 [50 51 52 53 54]]
(6L, 5L)
----------------------
[[0 1 2 3 4]]
(1L, 5L)
----------------------
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
(6L, 5L)
[[ 0  0  0  0  0]
 [10 10 10 10 10]
 [20 20 20 20 20]
 [30 30 30 30 30]
 [40 40 40 40 40]
 [50 50 50 50 50]]
(6L, 5L)


- 由于a和b的维数不同，根据规则1，需要让b的shape属性向a对齐，于是将b的shape属性前面加1，补齐为(1,5)。
- 这样加法运算的两个输入数组的shape属性分别为(6,1)和(1,5)，根据规则2，输出数组的各个轴的长度为输入数组各个轴的长度的最大值，可知输出数组的shape属性为(6,5)。

- 在执行“a+b”运算时，NumPy内部并不会真正将长度为1的轴用repeat()进行扩展，这样太浪费空间了。
- 由于这种广播计算很常用，因此NumPy提供了快速产生能进行广播运算的数组的ogrid对象。

- ogrid对象 和 mgrid对象

In [41]:
x,y = np.ogrid[:5,:5]
a,b = np.mgrid[:5,:5]
print x
print y
print '----------------------'
print a
print b

[[0]
 [1]
 [2]
 [3]
 [4]]
[[0 1 2 3 4]]
----------------------
[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [43]:
x,y = np.ogrid[:1:4j,:1:3j] # 当第三个参数为虚数时，它表示所返回的数组的长度，和“np.linspace()”类似    4j指有四个数
print x
print '----------------------'
print y

[[ 0.        ]
 [ 0.33333333]
 [ 0.66666667]
 [ 1.        ]]
----------------------
[[ 0.   0.5  1. ]]


- 利用ogrid的返回值，我们能很容易计算二元函数在等间距网格上的值。
- 下面是绘制三维曲面f(x,y) = x e^{x^2-y^2}的程序：

In [49]:
import numpy as np
from mayavi import mlab

x, y = np.ogrid[-2:2:20j, -2:2:20j]
z = x * np.exp( - x**2 - y**2)

pl = mlab.surf(x, y, z, warp_scale="auto")
mlab.axes(xlabel='x', ylabel='y', zlabel='z')
mlab.outline(pl)
mlab.show()

- 如果已经有了多个表示不同轴上的取值的一维数组。
- 想计算出它们所构成的网格上的每点的函数值，可以使用ix_()：

In [52]:
x = np.array([0,1,4,10])
y = np.array([2,3,8])
gy,gx = np.ix_(y,x) # 通过ix_()将数组x和y转换成能进行广播运算的二维数组
# 注意数组y对应广播运算结果中的第0轴，而数组x与第1轴对应
z = gx + gy
print x
print y
print gx
print gy
print z

[ 0  1  4 10]
[2 3 8]
[[ 0  1  4 10]]
[[2]
 [3]
 [8]]
[[ 2  3  6 12]
 [ 3  4  7 13]
 [ 8  9 12 18]]
